version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: swift-db
    restart: always
    environment:
      POSTGRES_DB: swift_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  swift-api:
    build: .
    container_name: swift-api
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  pg_data:


